### ISSUE TITLE
Improve UI of the website - Materail UI / Semnatic UI

### ISSUE THREAD

**Issue by shubhamkakkar** [PGPerfFarm/pgperffarm#24]
The project's functionality is very amazing and the incorporated features as well made, but the UI/UX of the website is far to be said good.

UI / UX can be easily improved just by targeting a few aspects of the website's component

PS  : "Graphic Designer Needed"

**Comment by MaleicAcid** [comment]
Hi shubhamkakkar,
I am very gald that you are interested in this project. Some components of this project are not really well designed. You can find all the components in the path "pgperffarm/front-end/src/component/".
I may not respond very promptly in the near future, but I am more than willing to listen to your specific improvements or suggestions.

**Comment by shubhamkakkar** [comment]
thanks for reverting..!
would let you know for sure regarding suggestions and improvement..!

and also whenever you are free for a word, would like to get some
suggestions for Development in the project and outside it as well and some
guidance for  GSOC as well..!


Thanks again

**Comment by shubhamkakkar** [comment]
hey, Sorry for disturbing you again..!
Can you share with me the link to your organisation's channel?
ie like gitter or slack etc.?

Thanks

**Comment by mw2q** [comment]
> hey, Sorry for disturbing you again..! Can you share with me the link to your organisation's channel? ie like gitter or slack etc.? Thanks 

We opened a perffarm channel on the postgresteam slack.
