### ISSUE TITLE
Is the project open for contributions?

### ISSUE THREAD

**Issue by LucianaMarques** [PGPerfFarm/pgperffarm#25]
Hello,

I came across with this project while looking into the 2018 GSoC projects, and found it very insteresting. I'd like to know whether it's open for contributions. I did see in #22 that the following tasks still need to be done:

* Use the community's user data interface for login verification

* Add test cases of different scale sets (scale=10,20...)

* Allow custom tests to be added

If contributions are welcome, I'll be happy to submit a PR in the following days. Thank you!

**Comment by mw2q** [comment]
Yes, contributions are welcome.  Thanks!
